name: Judy Kong
author: Judy Kong
baseurl: 
description: Judy Kong's Portfolio
github: http://www.github.com/judykong97
linkedin: http://www.linkedin.com/in/judy-kong-8aa80b128/
email: junhank[at]andrew.cmu.edu
location: 42°2'16"N   70°12'47"W

##Make sure to edit the above fields, especially for disqus.


rouge: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

collections:
  projects:
    title: true
    description: true
    note: true
    output: true
    permalink: /projects/:title

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "post"


